CREATE TABLE IF NOT EXISTS USERS (
    ID IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PHONE VARCHAR(30) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    ID IDENTITY PRIMARY KEY,
    GUEST_NAME VARCHAR(150) NOT NULL,
    GUEST_USERNAME VARCHAR(100) NOT NULL,
    ROOM_NUMBER VARCHAR(20) NOT NULL,
    CHECK_IN DATE NOT NULL,
    CHECK_OUT DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

INSERT INTO BOOKINGS (GUEST_NAME, GUEST_USERNAME, ROOM_NUMBER, CHECK_IN, CHECK_OUT, STATUS)
SELECT 'John Doe', 'guest1', '101', CURRENT_DATE, DATEADD('DAY', 3, CURRENT_DATE), 'CONFIRMED'
WHERE NOT EXISTS (SELECT 1 FROM BOOKINGS);

CREATE TABLE IF NOT EXISTS HELP_CHATS (
    ID IDENTITY PRIMARY KEY,
    ROOM_NUMBER VARCHAR(20) NOT NULL,
    GUEST_USERNAME VARCHAR(100) NOT NULL,
    RECIPIENT_ROLE VARCHAR(50) NOT NULL,
    RECIPIENT_USERNAME VARCHAR(100),
    SENDER_TYPE VARCHAR(20) NOT NULL,
    SENDER_USERNAME VARCHAR(100) NOT NULL,
    MESSAGE VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IS_READ_BY_STAFF BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS ROOMS (
    ID IDENTITY PRIMARY KEY,
    ROOM_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    ROOM_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    RATE DECIMAL(10, 2) NOT NULL
);

INSERT INTO ROOMS (ROOM_NUMBER, ROOM_TYPE, STATUS, RATE)
SELECT room_number, room_type, status, rate FROM (
    VALUES ('101', 'SINGLE', 'OCCUPIED', 120.00),
           ('102', 'DOUBLE', 'AVAILABLE', 180.00),
           ('201', 'SUITE', 'MAINTENANCE', 320.00),
           ('202', 'DOUBLE', 'AVAILABLE', 190.00),
           ('301', 'SINGLE', 'AVAILABLE', 115.00),
           ('302', 'SUITE', 'OCCUPIED', 350.00)
) AS seed(room_number, room_type, status, rate)
WHERE NOT EXISTS (SELECT 1 FROM ROOMS);

CREATE TABLE IF NOT EXISTS BILLS (
    ID IDENTITY PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    GUEST_NAME VARCHAR(150) NOT NULL,
    GUEST_USERNAME VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    ISSUED_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL
);

INSERT INTO BILLS (INVOICE_NUMBER, GUEST_NAME, GUEST_USERNAME, AMOUNT, STATUS, ISSUED_DATE, DUE_DATE)
SELECT invoice_number, guest_name, guest_username, amount, status, issued_date, due_date FROM (
    VALUES ('INV-1001', 'John Doe', 'guest1', 480.00, 'PENDING', CURRENT_DATE, DATEADD('DAY', 7, CURRENT_DATE)),
           ('INV-1002', 'Jane Smith', 'guest2', 320.50, 'PENDING', DATEADD('DAY', -2, CURRENT_DATE), DATEADD('DAY', 5, CURRENT_DATE)),
           ('INV-1003', 'Michael Brown', 'guest1', 780.75, 'PAID', DATEADD('DAY', -10, CURRENT_DATE), DATEADD('DAY', -3, CURRENT_DATE))
) AS seed(invoice_number, guest_name, guest_username, amount, status, issued_date, due_date)
WHERE NOT EXISTS (SELECT 1 FROM BILLS);
